Object.defineProperty(Object.prototype,"clone",{value:function(){function a(){}a.prototype=this;return new a}});function UB(){window.location="/12/updateBrowser/"}
if(!window.JSON||!window.Element||!document.querySelector)UB();else{window.UIEvent||(Event.prototype.stopPropagation=function(){this.cancelBubble=!0},Event.prototype.preventDefault=function(){this.returnValue=!1});Element.prototype.addEventListener||(window.addEventListener=Element.prototype.addEventListener=function(a,c){this.attachEvent("on"+a,c)},window.addEventListener=Element.prototype.removeEventListener=function(a,c){this.detachEvent("on"+a,c)});window.getComputedStyle||(window.getComputedStyle=
function(a){this.getPropertyValue=function(c){return"width"==c?a.offsetWidth:a.currentStyle[c]};return this});window.FormData||(FormData=Function);if(!window.name||"undefined"==window.name)window.name="";var N={obs:function(){var a={l:function(b,a){var d=this.e;"function"==typeof a&&(d[b]||(d[b]=[]),d[b].push(a))},f:function(b){var a=this.e[b];if(a)for(var d=Array.prototype.slice.call(arguments).slice(1),e=0,i=a.length;e<i;++e)a[e]&&a[e].apply(null,d)},r:function(a,c){if(this.e[a])if(c)for(var d=
0,e=this.e[a].length;d<e;++d)this.e[a][d]==c&&(this.e[a][d]=null);else delete this.e[a]}},c={};return function(b){if(c[b])return c[b];var f=a.clone();f.e={};return b?c[b]=f:f}}(),dom:function(a,c,b){function f(d,e,a){if("checkbox"==d.type||"radio"==d.type)d.checked=e?!0:!1;else if("input"==d.tagName.toLowerCase())d.value=e;else try{a?d.textContent=e:d.innerHTML=e}catch(b){}}a.bind=b.bind=function(d,a){this.addEventListener(d,a,!1);return this};a.unbind=b.unbind=function(d,a){this.removeEventListener(d,
a,!1);return this};b.addAttr=function(d,a){if(a)this.setAttribute(d,a);else for(var b in d){d[b].split&&(d[b]=d[b].split(" "));for(var a=this.getAttribute(b)||"",c=0,h=d[b].length;c<h;++c)0>a.indexOf(d[b][c])&&(a+=(0<a.length?" ":"")+d[b][c]);this.setAttribute(b,a)}return this};b.rmAttr=function(d,a){if("string"==typeof d)this.removeAttribute(d);else for(var b in d){d[b].split&&(d[b]=d[b].split(" "));for(var a=(this.getAttribute(b)||"").split(" "),c=0,h=a.length,f=[],k;c<h;++c){k=1;for(var j=0,m=
d[b].length;j<m;++j)a[c]==d[b][j]&&(k=0);k&&f.push(a[c])}f.length?this.setAttribute(b,2>f.length?a[0]:f.join(" ")):this.removeAttribute(b)}return this};return{find:function(a,b){return(b||c).querySelectorAll(a)},findOne:function(a,b){return(b||c).querySelector(a)},elm:function(a,b){var i=c.createElement(a);if(b)for(var g in b)i.setAttribute(g,b[g]);return i},set:function(a,b,c){if(a)if(a[0]instanceof Element)for(var g=0,h=a.length;g<h;++g)f(a[g],b,c);else f(a,b,c)},addAttr:function(a,b,c){if(a)if(a[0]instanceof
Element)for(var g=0,f=a.length;g<f;++g)a[g].addAttr(b,c);else a.addAttr(b,c)},rmAttr:function(a,b){if(a)if(a[0]instanceof Element)for(var c=0,f=a.length;c<f;++c)a[c].rmAttr(b);else a.rmAttr(b)}}}(window,document,Element.prototype),link:function(a,c){var b=new XMLHttpRequest;if(b&&a&&a.url){b.open(a.data?"post":"get",N.ok+a.url,!a.sync);window.name&&b.setRequestHeader("x-sid",window.name);if(a.data&&!1===a.data instanceof FormData)try{b.setRequestHeader("content-type","application/json"),a.data=JSON.stringify(a.data)}catch(f){b.abort();
c&&c(f);return}b.upload&&a.up&&(b.upload.onprogress=a.up);a.down&&(b.onprogress=a.down);b.onreadystatechange=function(){if(4==b.readyState){var a=b.A?"A":400>b.status?null:b.responseText||"E",e=b.getResponseHeader("x-sid");b.A=0;e&&(window.name="N"==e?"":e);if(c){e=null;if(!a)if(-1<(b.getResponseHeader("content-type")||"").indexOf("application/json"))try{e=JSON.parse(b.responseText)}catch(f){a=f}else e=b.responseText;c(a,e,b)}}};b.send(a.data);return function(){b.A=1;b.abort()}}},css:function(a){N.dom.findOne("head").appendChild(N.dom.elm("link",
{rel:"stylesheet",type:"text/css",href:N.ok+"/2/"+a}))},comp:function(a,c,b){(a="string"==typeof a?N.dom.findOne(a):a)&&"undefined"!==typeof c&&N.link({url:"/1/"+c},function(c,d){if(!c&&d){a.style.display="none";d[1]&&(a.innerHTML=d[1]);var e={$:a,obs:N.obs()},i=[],g={},h=0;if(d[2])for(var l=0,k=d[2].length;l<k;++l)N.css(d[2][l]);for(var j in d[0])g[h]=d[0][j],i[h]=j+"/"+j,++h;require(i,function(){i=arguments;for(var c in i)if(i[c]&&g[c])for(var d=0,f=g[c].length;d<f;++d){var h=i[c].clone();h.comp=
e;h.init&&h.init(g[c][d])}a.style.display="block";b&&b(null,e)})}})},state:function(){return function(){}}()};window.onerror=function(a,c,b){console.log(a+"\n"+c+"\n"+b)}};